work_dir: ./work_dir/kinetics/eggcn_-7_7_0-gcn_8
continue_train: True

# feeder
feeder: feeders.feeder_kinetics23.Feeder
train_feeder_args:
  data_path: /home/zkl/Documents/Data/kinetics/kinetics/train_data_joint.npy
  label_path: /home/zkl/Documents/Data/kinetics/kinetics/train_label.pkl
  debug: False
  random_choose: True
  random_move: True
  window_size: 256
  vel: True
  bone: True

test_feeder_args:
  data_path: /home/zkl/Documents/Data/kinetics/kinetics/val_data_joint.npy
  label_path: /home/zkl/Documents/Data/kinetics/kinetics/val_label.pkl
  debug: False

# model
model: model.eggcn23.Model
model_args:
  num_class: 400
  num_point: 18
  num_person: 2
  num_gcn_scales: 8
  num_groups: [7, 7, 0]
  graph: graph.kinetics.AdjMatrixGraph

# optimization
optimizer: sgd
weight_decay: 0.0001
base_lr: 0.1
step: [30, 50]

# training
num_epoch: 70
device: [0, 1, 2, 3]
batch_size: 64
forward_batch_size: 64
test_batch_size: 64
nesterov: True