
phase: test
weights: ./pre_trained/ntu/xsub/joint/weights-67-15611.pt

# feeder
feeder: feeders.feeder_ntu23.Feeder

test_feeder_args:
  data_path: /home/zkl/Documents/Data/nturgb+d/ntu/NTU60_CS.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  bone: False
  vel: False
  multi_input: True
  debug: False

# model
model: model.eggcn23.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  num_gcn_scales: 8
  num_groups: [7, 7, 0]
  groups: 1
  c1: 96
  graph: graph.ntu_rgb_d.AdjMatrixGraph

# training
device: [0, 1, 2, 3]
test_batch_size: 64