work_dir: ./work_dir/ntu/xsub/eggcn_mi-7_7_0-gcn_8
continue_train: True

# feeder
feeder: feeders.feeder_ntu23.Feeder
train_feeder_args:
  data_path: /home/zkl/Documents/Data/nturgb+d/ntu/NTU60_CS.npz
  split: train
  window_size: 64
  random_rot: True
  p_interval: [0.61, 1]
  vel: False
  bone: False
  debug: False
  multi_input: False

test_feeder_args:
  data_path: /home/zkl/Documents/Data/nturgb+d/ntu/NTU60_CS.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  debug: False

# model
model: model.eggcn23.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  num_gcn_scales: 8
  num_groups: [7, 7, 0]
  groups: 1
  c1: 96
  graph: graph.ntu_rgb_d.AdjMatrixGraph

# optim
weight_decay: 0.0005
base_lr: 0.1
step: [30, 50]
nesterov: True

# training
num_epoch: 70
device: [0, 1, 3]
batch_size: 192
forward_batch_size: 192
test_batch_size: 192